name: Contract CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    name: Build, Lint, and Test Contract
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: contract

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Rust Toolchain
        run: |
          rustup update stable
          rustup default stable
          rustup target add wasm32-unknown-unknown

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "contract -> target"


      - name: Unit Tests
        run: cargo test

      - name: WASM Build
        run: cargo build --target wasm32-unknown-unknown --release
